language: python
python:
  - "3.6"

script:
- echo "skipping tests"

deploy:
  provider: lambda
  function_name: tabutron
  region: eu-west-1
  role: arn:aws:iam::042447369539:role/lambda_basic_execution
  runtime: python3.6
  handler_name: lambda_handler
  secret_access_key:
    secure: DTfzonhpoFh8OGSyU9139VwSkgJC/Gv4ddI7kEZYs9nUsGqpMptnCB/O+RsWJZFkWjwD/mkrCxHuqHirn63TvM2RrYuCh4LVAlwXw22hpSO5HizV8Yfvi6OzDEX1CR1K148FE0oxpPw4vdJpJ+NqxnfhmYTCGMsyzV9fWtnuiuWMTvNSSuk2Y7QxqcuEJ5dzPAZbTcrG3ru4dykAbeptf4832zZxLf2OTsw4v8m7PuozwkzHB7OdEBzrGpxL3QeSoAFa8KnNoKTlF0R09HLjKB9fmbFm526ItP+9nBv41guLj89Qto6jG7Ix9p5E5v9HdM67Jg/2L4+wpniB4OooAKWPMHlG+fETmEp6cV1UaCFh6TZdkvl+ll+lyvL4BHmIKQi+xvMx8umuuodyjNKsb5++PmB5hBnK39mqShNsTrSY1zFqSaCYkcaVCFlAlb4r3QI79kHLZHecPVec1Nq+eJJ1EFJ8g93nWli2fiEp+IHs48z3fhfxmrUGhy18W6iEPUbHXLFSI/khTHyTr14wFv7wbNPNT4shy8WuXGLz6rrD1Pl6V3Q+q0R5vU0ZS9Cw2Y46re5JKDyjy86PRP90tqIngXKGQLrVgLNGYdvWsmcfukg85L6MMH0gNcDBLZumrjkcPAgZEm26s0n+/oetDVDmWLbbXoYPmRw7StUQRCM=
  access_key_id:
    secure: ZpPuoB4CPFbNa6RQk3IdpQ/XC75BCHdudK6y9q6x2oQWmkZw211qZrZhkmPIwefxOShs14L0dI4Oqd08XrvBa6dwj/8wMWDZsmyEF07s5s5fj9d3EhHHwNfl2UaXS/EeA1NaPpr+vR9aq9Ro+RyEPlbyxaPWOwdGAIDJpCflL9Nsy/8FJEkcvHt+8ljeuYipG/TwMPOyfe3a3EqYiMLywjRbWmYjh23/nR5urluttR0G4g/q5/A2kAOinXdjPt11FF5CehpSQacHceF2gqZ7Zb68V/4wCYj4qNYyR+ddk0oivAszRQEBvVpAWSvKV4IvcAtfHNAE/qVK8JsuBb2kJuSfoisITGwf77GTu2vnnAyWoD0TUkhWgpTJ9/ZPSH/8A7qiUbY66CePlwxB5j5FsitHSdaAOqObiFq1hC9Or0fEWeNPW75j+6w/nTRtC9HCDG+3gpbyiWQXLxCDQOWsvkrf1S7ko5uXAM+D6uYD5Cj9GtM8Juo66LZjKAVz4IGHVpxQga5PmyHek74ceNYsBUNlgq830fnOfE53MK1CDr6joLEzvPNa7qO0ZvQ/4OhWDJktOlklslOf6gVw8F/ad6VFlY4ovtNVgjrFKWBumh+hG+gE1D5LOS0KDSJodNI9+Ck0URw2sd/lpG+rlT2ZJl5azHKLJlwMTCIz9CyFyAI=
